start: _program
_program: stmt*

stmt: let_stmt
    | hot_block
    | expr_stmt
    | print_stmt

let_stmt: "let" CNAME (":" type_name)? "=" expr ";"
hot_block: "hot" "{" stmt* "}"
expr_stmt: expr ";"
print_stmt: "print" expr ";"

// Priority: unary > mul/div > add/sub
expr: term (ADDOP term)*
term: factor (MULOP factor)*
factor: NUMBER | FLOAT | BOOL | STRING | CNAME | MINUS factor
type_name: T_INT | T_FLOAT | T_BOOL | T_STRING
T_INT: "int"
T_FLOAT: "float"
T_BOOL: "bool"
T_STRING: "string"
 
ADDOP: "+" | "-"
MULOP: "*" | "/"
MINUS: "-"

BOOL: "true" | "false"
STRING: /"[^"]*"/
CNAME: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /[0-9]+/
FLOAT: /[0-9]+\.[0-9]+/

%ignore " "
%ignore "\n"
%ignore "\r"
%ignore "\t"
