start: _program
_program: stmt*

stmt: let_stmt
    | hot_block
    | expr_stmt
    | print_stmt

let_stmt: "let" CNAME "=" expr ";"
hot_block: "hot" "{" stmt* "}"
expr_stmt: expr ";"
print_stmt: "print" expr ";"

// Priority: unary > mul/div > add/sub
expr: term (ADDOP term)*
term: factor (MULOP factor)*
factor: NUMBER | CNAME | MINUS factor

ADDOP: "+" | "-"
MULOP: "*" | "/"
MINUS: "-"

CNAME: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /[0-9]+/

%ignore " "
%ignore "\n"
%ignore "\r"
%ignore "\t"
