start: _program
_program: stmt*

stmt: let_stmt
    | hot_block
    | expr_stmt
    | print_stmt
    | if_stmt

let_stmt: "let" CNAME (":" type_name)? "=" expr ";"
hot_block: "hot" block
block: "{" stmt* "}"
expr_stmt: expr ";"
print_stmt: "print" expr ";"
if_stmt: "if" "(" comparision ")" block ("else" else_branch)?
else_branch: if_stmt | block

// Priority: unary > mul/div > add/sub
expr: comparision
comparision: arith (CMPOP arith)*
arith: term (ADDOP term)*
term: factor (MULOP factor)*
factor: NUMBER | FLOAT | BOOL | STRING | CNAME | MINUS factor

CMPOP: "==" | "!=" | "<" | ">" | "<=" | ">="

type_name: T_INT | T_FLOAT | T_BOOL | T_STRING
T_INT: "int"
T_FLOAT: "float"
T_BOOL: "bool"
T_STRING: "string"
 
ADDOP: "+" | "-"
MULOP: "*" | "/"
MINUS: "-"

BOOL: "true" | "false"
STRING: /"[^"]*"/
CNAME: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /[0-9]+/
FLOAT: /[0-9]+\.[0-9]+/

%ignore " "
%ignore "\n"
%ignore "\r"
%ignore "\t"
